### ISSUE TITLE
Minio cannot re-use storage after upgarde

### ISSUE THREAD

**Issue by i-chvets** [canonical/mlflow-operator#112]
# Description
Minio cannot re-use storage after upgarde.
Minio upgrade is done using re-deploy method, i.e. Minio application is removed and then new charm is deployed.
When Minio application is removed, storage is detached. When new charm is deployed, a new clean storage is created. Old storage with existing data is still present in K8S cluster, but data is not transferred to new storage.

It seems Juju does not support re-use of existing storage for K8S deployment scenarios. As a result, there is no `juju deploy` option to attach existing storage to new charm/workload.

Regular upgrade does not work for MInio:
```
juju refresh minio --channel latest/edge
ERROR Juju on containers does not support updating storage on a statefulset.
The new charm's metadata contains updated storage declarations.
You'll need to deploy a new charm rather than upgrading if you need this change.
 not supported (not supported)
```

**Comment by DnPlas** [comment]
Thanks @i-chvets Could we please open this issue in the minio repository? This issue is not related to mlflow.
