### ISSUE TITLE
Using _on_event for update_status for mlflow v2.1.1

### ISSUE THREAD

**Issue by misohu** [canonical/mlflow-operator#133]
Sometimes mlflow gets minio credentials before the minio is actually available. This leads to errors as mlflow is trying to create default bucket at the startup. We catch the error and put charm to waiting status, however in some situations there is no other even emitting `_on_event`. 

We managed to fix this by adding `_on_event `to `update_status`. We might want to refactor in the future. 

We considered also deferring event but at the end it will be the same as the deferred event will be triggered on `update_status `event.

**Comment by i-chvets** [comment]
Fix is merged.
