### ISSUE TITLE
Data wont persist in relational DB for MLflow 2.1

### ISSUE THREAD

**Issue by misohu** [canonical/mlflow-operator#177]
For version 2.1 after container restart all model metadata are gone. Looks like relational DB is not used. Steps to reproduce: 

```
juju deploy mlflow --channel=2.1/edge --trust
# Manually create experiment in the UI
# Now remove the kubernetes pod 
kubectl delete po mlflow-server-0
# Wait a second juju controller will schedule a new pod 
# Access the ui and no experiment
```

I have tested also to store some models. Looks like the model is in MinIO but is missing metadata in relational DB.

**Comment by i-chvets** [comment]
Fix is merged.
