### ISSUE TITLE
reuse mariadb/mysql and minio charms

### ISSUE THREAD

**Issue by grobbie** [canonical/mlflow-operator#20]
The MLFlow bundle deploys a MariaDB server and a Minio instance - which if using with Charmed Kubeflow means duplication of services. Probably there is a documentation task needed to explain how to relate MLFlow to an existing MariaDB and Minio in order to avoid that duplication, but it might also require some code changes in order to assure separation of concerns around account credentials and ensure workload isolation.

**Comment by beliaev-maksim** [comment]
it is not recommended in production to use the same DB
