### ISSUE TITLE
MLflow integration with Kubeflow's Admission Webhook

### ISSUE THREAD

**Issue by nishant-dash** [canonical/mlflow-operator#205]
### Bug Description

I can't relate mlflow to kubeflow's admissions webhook. I dont see interfaces on both sides that make sense connecting at this point since they *both* seem to be providers of a pod-default interface.
```console
$ juju relate mlflow-server admission-webhook
ERROR no relations found
```

- for mlflow
```console
relations:
  provides:
    grafana-dashboard: grafana_dashboard
    metrics-endpoint: prometheus_scrape
    pod-defaults: pod-defaults
    secrets: secrets
  requires:
    dashboard-links: kubeflow_dashboard_links
    ingress: ingress
    object-storage: object-storage
    relational-db: mysql_client
 ```
 
 - for admissions webhook
 ```console
 relations:
  provides:
    pod-defaults: pod-defaults
  requires: {}
```

### To Reproduce

juju deploy kubeflow --channel=1.7/edge
juju deploy mlflow-server # stable        466
juju relate mlflow-server admission-webhook

### Environment

Kubeflow 1.7/edge
MLflow stable rev 466
Microk8s v1.24.17
Juju 2.9.44

### Relevant log output

```shell
ERROR no relations found
```

**Comment by misohu** [comment]
Hi in latest stable you no longer need Admission webhook for mlflow deployment. Please refer to this guide for standalone mlflow deployment https://discourse.charmhub.io/t/get-started-with-charmed-mlflow-v2/10693
