### ISSUE TITLE
Switch to mysql-k8s from mariadb

### ISSUE THREAD

**Issue by nishant-dash** [canonical/mlflow-operator#206]
### Bug Description

Currently the getting started guide mentions maraidb. Shouldn't we be using mysql at this point?
```sh
juju deploy mysql-k8s mlflow-db
juju relate mlflow-db mlflow-server
```

On a side note, I tried with mariadb but I get `ERROR no relations found`
But the relation with  mysql-k8s seems to work and I can spin up the mlflow server.

### To Reproduce

N/A

### Environment

N/A

### Relevant log output

```shell
N/A
```

**Comment by misohu** [comment]
Hi you can find the up to date guide here https://discourse.charmhub.io/t/get-started-with-charmed-mlflow-v2/10693

This latest stable one uses mysql
