### ISSUE TITLE
docs: TYPE YOUR QUESTION HERE

### ISSUE THREAD

**Issue by primandanugroho** [canonical/mlflow-operator#212]
*Please describe the question or issue you're facing with "Charmed MLflow documentation".*

---
*Reported from: https://documentation.ubuntu.com/charmed-mlflow/en/latest/?_ga=2.115813894.1660108425.1696081070-546273726.1696081070*

**Comment by NohaIhab** [comment]
closing this issue because it has no context
hi @primandanugroho
please file another issue with context if needed.
