### ISSUE TITLE
Update the docs for connecting to MLflow via Kubeflow

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/mlflow-operator#245]
### Context

Follow up from https://github.com/canonical/mlflow-operator/issues/244

The recommended way for deploying MLflow and Kubeflow should be with these 2 extra commands:
```bash
juju relate mlflow-server:ingress istio-pilot:ingress
juju relate mlflow-server:dashboard-links kubeflow-dashboard:links
```

And then MLflow should be accessible by clicking on the `MLflow` row in the CentralDashboard, which will redirect users to a new tab with MLflow (behind Dex).

### What needs to get done

We'll need to update the documentation to reflect 
1. the above code changes
2. how a user should access MLflow, when exposed with Kubeflow

### Definition of Done

1. The [current tutorial](https://documentation.ubuntu.com/charmed-mlflow/en/latest/tutorial/mlflow-kubeflow/) exposes the two new commands for integrating MLflow with Istio and the Dashboard
2. The above tutorial tells users how to connect to MLflow, when deployed with Kubeflow

**Comment by kimwnasptd** [comment]
cc @afgambin

**Comment by afgambin** [comment]
Triaged with high prio.

**Comment by ACodingfreak** [comment]
@kimwnasptd  - Is there any dependency with respect to juju and kf version for running below commands

```
juju relate mlflow-server:ingress istio-pilot:ingress
juju relate mlflow-server:dashboard-links kubeflow-dashboard:links
```

I tried above commands with juju: 2.4 and kf:1.7 and it failed

```
$ juju relate mlflow-server:ingress istio-pilot:ingress
$ juju relate mlflow-server:dashboard-links kubeflow-dashboard:links
ERROR application "kubeflow-dashboard" has no "links" relation
```

**Comment by ACodingfreak** [comment]
> @kimwnasptd - Is there any dependency with respect to juju and kf version for running below commands
> 
> ```
> juju relate mlflow-server:ingress istio-pilot:ingress
> juju relate mlflow-server:dashboard-links kubeflow-dashboard:links
> ```
> 
> I tried above commands with juju: 2.4 and kf:1.7 and it failed
> 
> ```
> $ juju relate mlflow-server:ingress istio-pilot:ingress
> $ juju relate mlflow-server:dashboard-links kubeflow-dashboard:links
> ERROR application "kubeflow-dashboard" has no "links" relation
> ```

Works with Juju 3.4 and CKF 1.8

One addon question will be currently I am running below commands to enable resource dispatcher to link mlflow with kubeflow. Do I still need to run these commands ?

```
juju deploy resource-dispatcher --channel 1.0/stable --trust
juju relate mlflow-server:secrets resource-dispatcher:secrets
juju relate mlflow-server:pod-defaults resource-dispatcher:pod-defaults
```
