### ISSUE TITLE
Unable to locate credentials

### ISSUE THREAD

**Issue by jcl3ng** [canonical/mlflow-operator#35]
Hello,
I have kubeflow and mlflow deployed with juju on a kubernetes cluster. I have set the mlfow tracking uri to the clusterip endpoint of the mlflow server and when trying to log the model, I get the following error:

```
NoCredentialsError: Unable to locate credentials
```

I also do not have the option to choose "mlflow-minio" in the configurations when starting the notebook server. Any help will be greatly appreciated

Thanks,

**Comment by ca-scribner** [comment]
hey sorry for the slow response.  Are you still stuck on this?  First guess is that you need to put your minio (or whatever artifact store mlflow is using) somewhere (environment variables I think are the primary method).  Have you set those anywhere?  That should be documented in the mlflow docs.

If I'm completely off base on this and you're still stuck, please respond!  And if you figured it out, let us know how and close this :)

**Comment by DomFleischmann** [comment]
Closing this issue because of no response, feel free to reopen if more information is needed.
