### ISSUE TITLE
Branch `track/1.13.1` using development version of `release-charm` action

### ISSUE THREAD

**Issue by ca-scribner** [canonical/mlflow-operator#39]
The current `release-charm` does not handle `charmcraft status` output that includes charmhub branches.  As a temp fix, this branch is set to a development version of the `release-charm` to fix this issue.  We should revert this hack and pin a released version of `release-charm` once one is available (see PR canonical/charming-actions#46).

**Comment by DnPlas** [comment]
Should we keep updating such track? If not let's close the issue @ca-scribner
